version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: static_web
    restart: unless-stopped
    volumes:
      - ./site:/usr/share/nginx/html      # Убрали :ro для возможности записи
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - wiki-net

  php:
    image: php:8.2-fpm-alpine
    container_name: static_php
    restart: unless-stopped
    volumes:
      - ./site:/usr/share/nginx/html      # Тот же путь для PHP
    networks:
      - wiki-net

networks:
  wiki-net:
    driver: bridge
